#!/usr/bin/perl
#
# buildd-checker: packages processor for buildd
# Copyright © 2012 Mike Thompson <mpthompson@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#######################################################################

use strict;
use warnings;

use Buildd qw(unlock_file);
use Buildd::Conf qw();
use Buildd::Checker;
use Sbuild::OptionsBase;

my $conf = Buildd::Conf::new();
exit 1 if !defined($conf);
my $options = Sbuild::OptionsBase->new($conf, "buildd-checker", "1");
exit 1 if !defined($options);
my $checker = Buildd::Checker->new($conf);
exit 1 if !defined($checker);

my $status = $checker->run();

$checker->close_log();

exit $status;

END {
    unlock_file($conf->get('HOME') . "/buildd-checker")
        if (defined($conf) &&
            defined($checker) &&
            defined($checker->get('Checker Lock')) &&
            $checker->get('Checker Lock'));
}

